FROM rust:1.73
WORKDIR /src/

RUN cargo install cargo-generate wasm-pack

RUN apt update && \
    apt install -y ca-certificates curl gnupg && \
    mkdir -p /etc/apt/keyrings && \
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
RUN echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_18.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
RUN apt update && apt install nodejs -y

COPY ./ ./

# tests (rust)
RUN wasm-pack build
RUN wasm-pack test --chrome --headless
RUN wasm-pack test --firefox --headless

WORKDIR /src/www/
RUN npm install
RUN npm run build
